apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-2qu0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-2qu0
    app.kubernetes.io/part-of: tkrw-pr714-0075-0067-app
  name: devfile-sample-2qu0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-2qu0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-2qu0
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0067-tenant/tkrw-pr714-0075-0067-app/devfile-sample-2qu0@sha256:8ee956217187db1f4a8755ed1ef7ba1570458444bac3fb4b63676ae4ce199865
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
